version: '3.9'
services:
  tag-server:
    image: 'gcr.io/cloud-tagging-10302018/gtm-cloud-image:stable'
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 512M
    environment:
      - CONTAINER_CONFIG=$CONTAINER_CONFIG
      - PREVIEW_SERVER_URL=https://${PREVIEW_SERVER_DOMAIN}
      - RUN_AS_PREVIEW_SERVER=false

  preview-server:
    image: 'gcr.io/cloud-tagging-10302018/gtm-cloud-image:stable'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 512M
    environment:
      - CONTAINER_CONFIG=$CONTAINER_CONFIG
      - RUN_AS_PREVIEW_SERVER=true

  proxy:
    image: caddy:2.6.4-alpine
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - $PWD/proxy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/proxy/logs:/etc/logs
      - caddy:/data
    environment:
      TAG_SERVER_DOMAIN: $TAG_SERVER_DOMAIN
      PREVIEW_SERVER_DOMAIN: $PREVIEW_SERVER_DOMAIN

volumes:
  caddy:
